import sys
import os
import socket
def report():
	os.system('touch report.txt')
	f = open("report.txt", "w")
	f.write("\n")
	f.write("\n")
	f.write("\t \t \t \t \t"+socket.gethostname()+" Report \t \t \t \t \t")
	f.close()
	f = open("report.txt", "a")
	os.system('date >> report.txt')
	f.write("\n")
	f.write("\n")
	f.write("\n")
	f.write("*****************************SYSTEM PROCESSES*****************************")
	f.write("\n")
	f.close()
	os.system('top -c -b|head -n 15|less +5 >>report.txt')
	f = open("report.txt", "a")
	f.write("\n")
	f.write("*****************************SYSTEM MEMORY STATUS**************************")
	f.write("\n")
	f.close()
	os.system('free -m >>report.txt')
	f = open("report.txt", "a")
	f.write("\n")
	f.write("*****************************MOUNT DEVICE STATUS***************************")
	f.write("\n")
	f.close()
	os.system('df -h >>report.txt')
	f = open("report.txt", "a")
	f.write("\n")
	f.write("*****************************RUNNING SERVICES LIST*************************")
	f.write("\n")
	f.close()
	os.system('systemctl list-units --type service --all|grep running >>report.txt')
	f = open("report.txt", "a")
	f.write("\n")
	f.write("*****************************NETWORK STATUS********************************")
	f.write("\n")
	f.close()
	os.system('ip addr >>report.txt')
	f = open("report.txt", "a")
	f.write("\n")
	f.write(" ||  INFORMATION SHOULD BE  FREE  ||")
	print('HAVE A NICE DAY :)')	

report()


